name: learn-workflow
run-name: ${{ github.actor }} is learning
on: [push]
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: check out repo to the runner
        uses: actions/checkout@v4  
      - name: run script
        run: node index.js
        env: 
          ENV: development
